# Generated by Django 2.2.7 on 2020-01-24 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='tweet',
            new_name='associated_tweet',
        ),
    ]
