# Generated by Django 3.0.2 on 2020-01-24 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0007_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
    ]
