# Generated by Django 2.2.7 on 2020-01-25 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweets', '0009_comment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='dislikes',
            field=models.ManyToManyField(related_name='disliked_tweets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tweet',
            name='likes',
            field=models.ManyToManyField(related_name='liked_tweets', to=settings.AUTH_USER_MODEL),
        ),
    ]
