# Generated by Django 2.2.7 on 2020-01-25 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_notification_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='created',
        ),
    ]
